import React from "react"
import Container from "../components/Container"
import Diagram from "../components/Diagram"
import Features from "../components/Features"
import Hero from "../components/Hero"
import Layout from "../components/Layout"
import Team from "../components/Team"
import claimDiagram from "../images/diagrams/claim.svg"
import lockDiagram from "../images/diagrams/lock.svg"
import sellDiagram from "../images/diagrams/sell.svg"

const IndexPage = () => (
  <Layout>
    <Hero />

    <Diagram
      mode="right"
      img={lockDiagram}
      title="Deposit your interest-bearing tokens"
      text="Tokenise the yield generated by your interest-bearing tokens. APWine splits your interest-bearing assets into Principal Tokens and Future Yield Tokens."
    />
    <Diagram
      mode="left"
      img={sellDiagram}
      title="Sell your APYs ahead of time"
      text="Sell, buy and trade Future Yield Tokens ahead of time to speculate on the APY of DeFi platforms."
    />
    <Diagram
      mode="right"
      img={claimDiagram}
      title="Claim your yield at maturity"
      text="Claim your yield at maturity by burning your Future Yield Tokens."
    />

    <Container children={<Features />} className="mt-40" />

    <Container children={<Team />} className="mt-40" />
  </Layout>
)

export default IndexPage
