import React from "react"

import classnames from "classnames"

import { FaBalanceScale } from "react-icons/fa"
import { BiCoin } from "react-icons/bi"
import { Title, Paragraph } from "./Text"

const Feature = ({ icon: Icon, title, description, className = undefined }) => (
    <div className={classnames("flex flex-col", className)}>
        <Icon className="text-blue-500" size="5rem" />
        <Title className="mt-2">{ title }</Title>
        <Paragraph className="mt-2">{ description }</Paragraph>
    </div>
)

const Features = () => (
    <div>
        <Feature
            icon={BiCoin}
            title="Yield Tokenization"
            description="Speculate on the evolution of the yield generated by different DeFi protocols." />
        <Feature
            className="mt-16"
            icon={FaBalanceScale}
            title="Hedging"
            description="Hedge your risk on your passive revenue, converting it into futures." />
    </div>
)

export default Features