import React from "react"

const Hero = () => (
  <div className="flex flex-col items-center w-full max-w-2xl px-8 mx-auto mt-16 mb-32 text-white md:mt-14 md:mb-24 md:px-0">
    <span className="text-4xl font-bold text-center md:text-5xl glow-text text-glow">
      The protocol allowing you to trade unrealised yield.
    </span>
    {/*
        TODO: add on Mainnet beta
        <div className="flex flex-col items-center mt-8 space-y-2">
            <span className="text-sm tracking-widest uppercase font-text">Total value locked</span>
            <span className="px-6 py-4 text-5xl font-bold bg-opacity-100 bg-primary-400 rounded-xl">589,234,583.394$</span>
        </div>
        */}
    <span className="mt-8 text-sm font-light text-center font-text">
      Speculate on the evolution of the yield generated by different DeFi
      protocols. Hedge your risk on your passive revenue, converting it into
      futures.
    </span>
    <div className="flex flex-col items-center mt-8 space-y-2 text-sm sm:flex-row sm:space-y-0 sm:space-x-2">
      <a
        href="https://lbp.apwine.fi"
        target="_blank"
        rel="noopener noreferrer"
        className="px-8 py-3 transition duration-300 bg-gradient-to-br from-primary-300 to-primary-200 rounded-xl hover:opacity-75"
      >
        Enter LBP
      </a>
      <a
        href="https://gov.apwine.fi"
        target="_blank"
        rel="noopener noreferrer"
        className="px-8 py-3 transition duration-300 hover:text-primary-200"
      >
        Explore more
      </a>
    </div>
  </div>
)

export default Hero
