import React from "react"

const Hero = () => (
    <div className="flex flex-col items-center text-white w-full max-w-2xl mx-auto mt-14 mb-24">
        <span className="text-5xl font-bold glow-text text-center">The protocol allowing you to trade unrealised yield.</span>
        <div className="flex flex-col items-center space-y-2 mt-8">
            <span className="font-text uppercase tracking-widest text-sm">Total value locked</span>
            <span className="px-6 py-4 bg-primary bg-opacity-50 rounded-xl text-5xl font-bold">589,234,583.394$</span>
        </div>
        <span className="font-text font-light text-sm text-center mt-8">Speculate on the evolution of the yield generated by different DeFi protocols. Hedge you risk on your passive revenue, converting it into futures.</span>
        <div className="flex flex-row items-center mt-8 text-sm space-x-2">
            <a href="" className="px-8 py-3 bg-gradient-to-br from-primary-dark to-primary rounded-xl">Enter platform</a>
            <a href="" className="px-8 py-3 ">Explore more</a>
        </div>
    </div>
)

export default Hero