import React from "react";
import { Link } from "gatsby";

import HeroVideo from "../../videos/hero-desktop.mp4";
import HeroVideoTablet from "../../videos/hero-tablet.mp4";
import HeroVideoMobile from "../../videos/hero-mobile.mp4";

import "../../styles/sections/homepage/hero.scss";

const HeroSection = () => {
  return (
    <section className="hero-section">
      <div className="hero-bg">
        <video
          autoPlay
          muted
          className="desktop"
        >
          <source src={HeroVideo} type="video/mp4" />
        </video>
        <video
          autoPlay
          muted
          className="tablet"
        >
          <source src={HeroVideoTablet} type="video/mp4" />
        </video>
        <video
          autoPlay
          muted
          className="mobile"
        >
          <source src={HeroVideoMobile} type="video/mp4" />
        </video>
      </div>

      <div className="container">
        <div className="row">
          <div className="content-wrap">
            <h1>The derivatives layer for DeFi yield</h1>
            <div className="text-wrap">
              <p>
                Speculate on the evolution of the yield generated by different
                DeFi protocols. Hedge your risk on your passive revenues.
              </p>
            </div>
            <div className="btn-wrap">
              <Link to="/" className="btn btn--primary">
                V1 Page
              </Link>
              <Link to="/" className="btn btn--primary-border">
                Explore more
              </Link>
            </div>
          </div>
        </div>
      </div>
    </section>
  );
};

export default HeroSection;
